import bcrypt from 'bcryptjs'

const data = 
{
    products:
    [
        {
            name: 'Nike Predator',
            category: 'Sneakers',
            image: '/assets/img/shoes1.png',
            price: 224.99,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            inStock: 9,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [42, 43, 45, 46],
        },
        
        {
            name: 'Asics GEL-KAYANO',
            category: 'Running shoes',
            image: '/assets/img/shoes7.png',
            price: 329.49,
            brand: 'Asics',
            rating: 4.3,
            numReviews: 25,
            inStock: 19,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [39, 40, 41, 42, 44, 45],
        },
        {
            name: 'Zalomon Speedcross 5 GTX',
            category: 'Running shoes',
            image: '/assets/img/shoes8.png',
            price: 319.99,
            brand: 'Zalomon',
            rating: 4.9,
            numReviews: 52,
            inStock: 5,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [39, 41, 42, 43],
        },
        {
            name: 'Under Armor Curry 2',
            category: 'Sneakers',
            image: '/assets/img/shoes9.png',
            price: 499.99,
            brand: 'Under Armor',
            rating: 4.4,
            numReviews: 91,
            inStock: 10,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [37, 39, 40, 41, 42, 43],
        },
        {
            name: 'Alvo black shiny leather',
            category: 'Patent leather',
            image: '/assets/img/shoes10.png',
            price: 529.99,
            brand: 'Alvo',
            rating: 4.4,
            numReviews: 25,
            inStock: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [40, 41, 42, 43, 44, 45, 46, 47],
        },
        {
            name: 'Nike React Miler',
            category: 'Sneakers',
            image: '/assets/img/shoes2.png',
            price: 214.99,
            brand: 'Nike',
            rating: 4.2,
            numReviews: 14,
            inStock: 16,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [40, 41, 44, 45],
        },
        {
            name: 'Tom Tailor Shoes',
            category: 'Casual',
            image: '/assets/img/shoes3.png',
            price: 199.99,
            brand: 'Tom Tailor',
            rating: 3.9,
            numReviews: 21,
            inStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [42, 43],
        },
        {
            name: 'Nike Air Max 2090',
            category: 'Sneakers',
            image: '/assets/img/shoes4.png',
            price: 299.99,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 36,
            inStock: 15,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [38, 39, 40, 41, 42, 43, 44, 45, 47],
        },
        {
            name: 'Adidas Superstar',
            category: 'Trainers',
            image: '/assets/img/shoes5.png',
            price: 369.49,
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 18,
            inStock: 7,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [39, 41, 42, 43],
        },
        {
            name: 'Neven High Stale Black',
            category: 'Casual',
            image: '/assets/img/shoes6.png',
            price: 224.49,
            brand: 'Neven High',
            rating: 3.7,
            numReviews: 62,
            inStock: 17,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
            sizes: [39, 41, 42, 43],
        },
    ],
    users: 
    [
        {
            name: 'Jakub',
            email: 'admin@example.com',
            password: bcrypt.hashSync('admin', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('123', 8),
            isAdmin: false,
        }
    ],
}

export default data;