const data = 
{
    products:
    [
        {
            _id: 1,
            name: 'Nike Predator',
            category: 'Sneakers',
            image: '/assets/img/shoes1.png',
            price: '224.99$',
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            inStock: 1,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 2,
            name: 'Nike React Miler',
            category: 'Sneakers',
            image: '/assets/img/shoes2.png',
            price: '215$',
            brand: 'Nike',
            rating: 4.2,
            numReviews: 14,
            inStock: 16,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 3,
            name: 'Tom Tailor Shoes',
            category: 'Casual',
            image: '/assets/img/shoes3.png',
            price: '199.99$',
            brand: 'Tom Tailor',
            rating: 3.9,
            numReviews: 21,
            inStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 4,
            name: 'Nike Air Max 2090',
            category: 'Sneakers',
            image: '/assets/img/shoes4.png',
            price: '499.99$',
            brand: 'Nike',
            rating: 4.8,
            numReviews: 36,
            inStock: 5,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 5,
            name: 'Adidas Superstar',
            category: 'Trainers',
            image: '/assets/img/shoes5.png',
            price: '369.49$',
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 18,
            inStock: 7,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 6,
            name: 'Nike Predator',
            category: 'Sneakers',
            image: '/assets/img/shoes1.png',
            price: '224.99$',
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            inStock: 0,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 7,
            name: 'Nike React Miler',
            category: 'Sneakers',
            image: '/assets/img/shoes2.png',
            price: '215$',
            brand: 'Nike',
            rating: 4.2,
            numReviews: 14,
            inStock: 14,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
        {
            _id: 8,
            name: 'Tom Tailor Shoes',
            category: 'Casual',
            image: '/assets/img/shoes3.png',
            price: '199.99$',
            brand: 'Tom Tailor',
            rating: 3.9,
            numReviews: 21,
            inStock: 31,
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dapibus felis eu interdum consectetur. Cras eget diam eget lorem facilisis bibendum vitae nec augue. Etiam sed ipsum ac elit pharetra interdum a non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed tincidunt, mauris at congue efficitur, ante erat pretium lorem, vel rhoncus lacus nibh et odio. Etiam a finibus sapien, ut porta orci. Maecenas ut placerat ligula. In id imperdiet augue, at cursus urna.',
        },
    ]
}

export default data;