const data = 
{
    products:
    [
        {
            _id: 1,
            name: 'Nike Predator',
            category: 'Sneakers',
            image: '/assets/img/shoes1.png',
            price: '224.99zł',
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Red nike sneakers made of natural materials',
        },
        {
            _id: 2,
            name: 'Nike React Miler',
            category: 'Sneakers',
            image: '/assets/img/shoes2.png',
            price: '215zł',
            brand: 'Nike',
            rating: 4.2,
            numReviews: 14,
            description: 'Sportswear designed to be lightweight and ultra-durable',
        },
        {
            _id: 3,
            name: 'Tom Tailor Shoes',
            category: 'Casual',
            image: '/assets/img/shoes3.png',
            price: '199.99zł',
            brand: 'Tom Tailor',
            rating: 3.9,
            numReviews: 21,
            description: 'Casual leather shoes for daily use',
        },
        {
            _id: 4,
            name: 'Nike Air Max 2090',
            category: 'Sneakers',
            image: '/assets/img/shoes4.png',
            price: '499.99zł',
            brand: 'Nike',
            rating: 4.8,
            numReviews: 36,
            description: 'Newest edition of Air Max series designed to perform the best possible',
        },
        {
            _id: 5,
            name: 'Adidas Superstar',
            category: 'Trainers',
            image: '/assets/img/shoes5.png',
            price: '369.49zł',
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 18,
            description: 'Adidas shoes perfect for common daily use',
        },
        {
            _id: 6,
            name: 'Nike Predator',
            category: 'Sneakers',
            image: '/assets/img/shoes1.png',
            price: '224.99zł',
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Red nike sneakers made of natural materials',
        },
        {
            _id: 7,
            name: 'Nike React Miler',
            category: 'Sneakers',
            image: '/assets/img/shoes2.png',
            price: '215zł',
            brand: 'Nike',
            rating: 4.2,
            numReviews: 14,
            description: 'Sportswear designed to be lightweight and ultra-durable',
        },
        {
            _id: 8,
            name: 'Tom Tailor Shoes',
            category: 'Casual',
            image: '/assets/img/shoes3.png',
            price: '199.99zł',
            brand: 'Tom Tailor',
            rating: 3.9,
            numReviews: 21,
            description: 'Casual leather shoes for daily use',
        },
        {
            _id: 9,
            name: 'Nike Air Max 2090',
            category: 'Sneakers',
            image: '/assets/img/shoes4.png',
            price: '499.99zł',
            brand: 'Nike',
            rating: 4.8,
            numReviews: 36,
            description: 'Newest edition of Air Max series designed to perform the best possible',
        },
        {
            _id: 10,
            name: 'Adidas Superstar',
            category: 'Trainers',
            image: '/assets/img/shoes5.png',
            price: '369.49zł',
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 18,
            description: 'Adidas shoes perfect for common daily use',
        },
        {
            _id: 11,
            name: 'Nike Predator',
            category: 'Sneakers',
            image: '/assets/img/shoes1.png',
            price: '224.99zł',
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Red nike sneakers made of natural materials',
        },
        {
            _id: 12,
            name: 'Nike React Miler',
            category: 'Sneakers',
            image: '/assets/img/shoes2.png',
            price: '215zł',
            brand: 'Nike',
            rating: 4.2,
            numReviews: 14,
            description: 'Sportswear designed to be lightweight and ultra-durable',
        },
        {
            _id: 13,
            name: 'Tom Tailor Shoes',
            category: 'Casual',
            image: '/assets/img/shoes3.png',
            price: '199.99zł',
            brand: 'Tom Tailor',
            rating: 3.9,
            numReviews: 21,
            description: 'Casual leather shoes for daily use',
        },
        {
            _id: 14,
            name: 'Nike Air Max 2090',
            category: 'Sneakers',
            image: '/assets/img/shoes4.png',
            price: '499.99zł',
            brand: 'Nike',
            rating: 4.8,
            numReviews: 36,
            description: 'Newest edition of Air Max series designed to perform the best possible',
        },
        {
            _id: 15,
            name: 'Adidas Superstar',
            category: 'Trainers',
            image: '/assets/img/shoes5.png',
            price: '369.49zł',
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 18,
            description: 'Adidas shoes perfect for common daily use',
        }
    ]
}

export default data;